package exceptionHandling0;

public class Example06 {

	public static void main(String[] args) {
		try {
			System.out.println("in try");
		}
		catch(ArithmeticException ae) {
			System.out.println("in catch");
		}
		finally {
			System.out.println("in finally");
		}
		System.out.println("after try catch-finally");
	}
}